let DHIS_BASE_API_URL = process.env.REACT_APP_DHIS_BASE_API_URL;
let APP_BASE_URL =
    process.env.REACT_APP_APP_BASE_URL || 'http://41.89.94.99:3000';
let emms = [
    {
        page: 'Global',
        level: 'All',
        name: 'Levels list',
        id: 'all__levels_list',
        url: `${DHIS_BASE_API_URL}/organisationUnitLevels.json?paging=false&fields=name,level`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'Organisation unit details',
        id: 'all__org_unit_details',
        local_url: `${APP_BASE_URL}/api/common/organisationUnit`,
        url: `${DHIS_BASE_API_URL}/organisationUnits`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'Counties list',
        id: 'all__counties_list',
        local_url: `${APP_BASE_URL}/api/common/counties`,
        url: `${DHIS_BASE_API_URL}/organisationUnits.json?filter=level:eq:2&fields=id,name,level&paging=false`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'Subcounties list',
        id: 'all__subcounties_list',
        local_url: `${APP_BASE_URL}/api/common/subcounties`,
        url: `${DHIS_BASE_API_URL}/organisationUnits.json?filter=level:eq:3&fields=id,name,level,parent&paging=false`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'Wards list',
        id: 'all__wards_list',
        local_url: `${APP_BASE_URL}/api/common/wards`,
        url: `${DHIS_BASE_API_URL}/organisationUnits.json?filter=level:eq:4&fields=id,name,level,parent&paging=false`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'Facilities list',
        id: 'all__facilities_list',
        local_url: `${APP_BASE_URL}/api/common/facilities`,
        url: `${DHIS_BASE_API_URL}/organisationUnits.json?filter=level:eq:5&fields=id,name,level,parent&paging=false`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'CUs list',
        id: 'all__cus_list',
        local_url: `${APP_BASE_URL}/api/common/community-units`,
        url: `${DHIS_BASE_API_URL}/organisationUnits.json?filter=level:eq:6&fields=id,name,level,parent&paging=false`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'MFL codes',
        id: 'all__mfl_codes',
        local_url: `${APP_BASE_URL}/api/common/mfl-codes`,
        url: `${DHIS_BASE_API_URL}/organisationUnits.json?fields=id,code&paging=false`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'User details',
        id: 'all__user_details',
        local_url: `${APP_BASE_URL}/api/common/defaults`,
        url: `${DHIS_BASE_API_URL}/me.json`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'Program Commodities',
        id: 'all__commodities',
        local_url: `${APP_BASE_URL}/api/common/commodities`,
        url: `${DHIS_BASE_API_URL}/dataSets/ppdqEN91qZs.json?fields=dataSetElements[dataElement[id,name]]`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'Facilities assigned form',
        id: 'all__mcf_orgunits',
        local_url: `${APP_BASE_URL}/api/common/mcf-facilities`,
        url: `${DHIS_BASE_API_URL}/dataSets.json?fields=id,name,organisationUnits[id,name,code,level]&filter=id:ilike:ppdqEN91qZs&paging=false`,
        Filters: '',
        Notes: ''
    },
    {
        page: 'Global',
        level: 'All',
        name: 'Expected Reports',
        id: 'all__expected_reports',
        local_url: `${APP_BASE_URL}/api/common/expected-reports`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.EXPECTED_REPORTS`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        Filters: '',
        Notes: ''
    },
    {
        page: 'Dashboard',
        level: 'All',
        name: 'Stock Status',
        id: 'all__stock_status',
        local_url: `${APP_BASE_URL}/api/dashboard/stockstatus`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:SFwHgXxyaBX;uHSqkMzQWbJ;m2Dxu9fe9Ps;VA3KZphR8Dc;h1NaQphYTFv;rdUP34gG5z7;gkY7xYvyV01;snkYSLUGXk6;tFikgcVkTSr;n8B0vvf1PCW;aAHIH8QcdoF;P9PNWcxgAHG;QkKle90Kwfs;IjHwXyp22GE;zdEZm4Z5KML;JTrO9OYowPR;ffP7j9XBixo;tAcjBkf9vqR;MVFnuEjVRIH;qOKc8iEdsZ8;mLJhBXN6d3m;JRnL0o1E7K8;PcX1hwl7aQD.n8XlCFUpWOG;Klw6Oa18M4Y.n8XlCFUpWOG;QGugDSQXwPR.n8XlCFUpWOG;t8vd4GgcRmh.n8XlCFUpWOG;QYT9nPwdqOz.n8XlCFUpWOG;xvX0hsq7F8j.n8XlCFUpWOG;GOFxghdlf5n.n8XlCFUpWOG;BT8vV7Z7anH.n8XlCFUpWOG;Ss60yT7k8lU.n8XlCFUpWOG;WiygygYRqs7.n8XlCFUpWOG;hBItOmE0ybe.n8XlCFUpWOG;WbDKZsPHAOK.n8XlCFUpWOG;mvrXlqZoM0a.n8XlCFUpWOG;v4Ql5RkIJ7M.n8XlCFUpWOG;v424EPiNCAt.n8XlCFUpWOG;IXOZKkAxEFu.n8XlCFUpWOG;rEQd6IDeXWT.n8XlCFUpWOG;DclammcSWra.n8XlCFUpWOG;l5mDKpIdb3U.n8XlCFUpWOG;jiOLjNl8eXE.n8XlCFUpWOG;VwIbS3g8kPG.n8XlCFUpWOG;qoEFejcajz1.n8XlCFUpWOG;SNj7ETKcFO3.QvctQfKAQn3;Rmx1tNUwJyb.QvctQfKAQn3;TjTv4RDUy8A.QvctQfKAQn3;DJC8qxQeJA6.QvctQfKAQn3;G8JcgB3ZHT8.QvctQfKAQn3;Slds2fjm6k5.QvctQfKAQn3;mp0OYo756gW.QvctQfKAQn3;BG8rAWc2pPP.QvctQfKAQn3;C5HRQXl977d.QvctQfKAQn3;lcqBs8Qopdx.QvctQfKAQn3;QqXgC8XD3IF.QvctQfKAQn3;VuGtfH5eHug.QvctQfKAQn3;VJRNI5qVkN1.QvctQfKAQn3;GmDKO6zO1u9.QvctQfKAQn3;f1SlNJAAxMr.QvctQfKAQn3;vu1eIRte2X7.QvctQfKAQn3;PQks88LiY83.QvctQfKAQn3;fssTWMkgFm3.QvctQfKAQn3;NKHbkWxRihZ.QvctQfKAQn3;ZkMqBIlB6h4.QvctQfKAQn3;JGcQHMwZP0b.QvctQfKAQn3;RDb5SFas36A.QvctQfKAQn3`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: '',
        Filters: '',
        Notes: ''
    },
    {
        page: 'Dashboard',
        level: 'All',
        name: 'MOS by commodity',
        id: 'all__mos_by_commodity',
        local_url: `${APP_BASE_URL}/api/dashboard/mos-by-commodity`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:SFwHgXxyaBX;uHSqkMzQWbJ;m2Dxu9fe9Ps;VA3KZphR8Dc;h1NaQphYTFv;rdUP34gG5z7;gkY7xYvyV01;snkYSLUGXk6;tFikgcVkTSr;n8B0vvf1PCW;aAHIH8QcdoF;P9PNWcxgAHG;QkKle90Kwfs;IjHwXyp22GE;zdEZm4Z5KML;JTrO9OYowPR;ffP7j9XBixo;tAcjBkf9vqR;MVFnuEjVRIH;qOKc8iEdsZ8;mLJhBXN6d3m;JRnL0o1E7K8`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: '',
        Notes: ''
    },
    {
        page: 'Dashboard',
        level: 'All',
        name: 'Facilities stock status (count)',
        id: 'all__facilities_stock_status',
        local_url: `${APP_BASE_URL}/api/dashboard/facility-stock-status`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:SFwHgXxyaBX;uHSqkMzQWbJ;m2Dxu9fe9Ps;VA3KZphR8Dc;h1NaQphYTFv;rdUP34gG5z7;gkY7xYvyV01;snkYSLUGXk6;tFikgcVkTSr;n8B0vvf1PCW;aAHIH8QcdoF;P9PNWcxgAHG;QkKle90Kwfs;IjHwXyp22GE;zdEZm4Z5KML;JTrO9OYowPR;ffP7j9XBixo;tAcjBkf9vqR;MVFnuEjVRIH;qOKc8iEdsZ8;mLJhBXN6d3m;JRnL0o1E7K8`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 5,
        Filters: '',
        Notes: ''
    },

    {
        page: "Stock status",
        level: "County",
        name: "Adrenaline Injection 1mg/ml (Ampoule)",
        id: "county__adrenaline_injection_1mgml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/SNj7ETKcFO3`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;SNj7ETKcFO3.QvctQfKAQn3;PcX1hwl7aQD.n8XlCFUpWOG;SFwHgXxyaBX`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Albendazole Tab. 400mg (Tablet)",
        id: "county__albendazole_tab_400mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/Rmx1tNUwJyb`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;Rmx1tNUwJyb.QvctQfKAQn3;Klw6Oa18M4Y.n8XlCFUpWOG;uHSqkMzQWbJ`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Amoxicillin Capsules, 500mg (Capsule)",
        id: "county__amoxicillin_capsules_500mg_capsule",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/TjTv4RDUy8A`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;TjTv4RDUy8A.QvctQfKAQn3;QGugDSQXwPR.n8XlCFUpWOG;m2Dxu9fe9Ps`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Amoxicillin Dispersible Tablets, 250mg (Tablet)",
        id: "county__amoxicillin_dispersible_tablets_250mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/DJC8qxQeJA6`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;DJC8qxQeJA6.QvctQfKAQn3;t8vd4GgcRmh.n8XlCFUpWOG;VA3KZphR8Dc`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Benzyl penicillin Injection 1 MU (Vial)",
        id: "county__benzyl_penicillin_injection_1_mu_vial",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/G8JcgB3ZHT8`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;G8JcgB3ZHT8.QvctQfKAQn3;QYT9nPwdqOz.n8XlCFUpWOG;h1NaQphYTFv`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Benzyl penicillin Injection 5 MU (Vial)",
        id: "county__benzyl_penicillin_injection_5_mu_vial",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/Slds2fjm6k5`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;Slds2fjm6k5.QvctQfKAQn3;xvX0hsq7F8j.n8XlCFUpWOG;rdUP34gG5z7`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Chlorhexidine gel, 7.1% (as digluconate) (20 g tube) (Tube)",
        id: "county__chlorhexidine_gel_71_as_digluconate_20g_tube",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/mp0OYo756gW`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;mp0OYo756gW.QvctQfKAQn3;GOFxghdlf5n.n8XlCFUpWOG;gkY7xYvyV01`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Gentamicin Injection, 40mg/2ml (Ampoule)",
        id: "county__gentamicin_injection_40mg2ml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/BG8rAWc2pPP`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;BG8rAWc2pPP.QvctQfKAQn3;BT8vV7Z7anH.n8XlCFUpWOG;snkYSLUGXk6`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Hydrocortisone Injection 100mg (Vial)",
        id: "county__hydrocortisone_injection_100mg_vial",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/C5HRQXl977d`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;C5HRQXl977d.QvctQfKAQn3;Ss60yT7k8lU.n8XlCFUpWOG;tFikgcVkTSr`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Insulin, Premix (short acting +intermediate acting) Human [30 regular + 70 NPH) Injection 10ml Bottle (Vial /Bottle)",
        id: "county__insulin_premix_short_acting_intermediate_acting_human_injection_10ml_bottle_vial",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/lcqBs8Qopdx`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;lcqBs8Qopdx.QvctQfKAQn3;WiygygYRqs7.n8XlCFUpWOG;n8B0vvf1PCW`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Loratadine Tablets, 10mg (Tablet)",
        id: "county__loratadine_tablets_10mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/QqXgC8XD3IF`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;QqXgC8XD3IF.QvctQfKAQn3;hBItOmE0ybe.n8XlCFUpWOG;aAHIH8QcdoF`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Magnesium Sulphate Injection, 500mg/mL (50%), 10mL (Ampoule, 10ml)",
        id: "county__magnesium_sulphate_injection_500mgml_50_10ml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/VuGtfH5eHug`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;VuGtfH5eHug.QvctQfKAQn3;WbDKZsPHAOK.n8XlCFUpWOG;P9PNWcxgAHG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Metronidazole Tablet, 400mg (Tablet)",
        id: "county__metronidazole_tablet_400mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/VJRNI5qVkN1`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;VJRNI5qVkN1.QvctQfKAQn3;mvrXlqZoM0a.n8XlCFUpWOG;QkKle90Kwfs`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Midazolam Injection 5mg/ml, 3ml (Ampoule)",
        id: "county__midazolam_injection_5mgml_3ml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/GmDKO6zO1u9`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;GmDKO6zO1u9.QvctQfKAQn3;v4Ql5RkIJ7M.n8XlCFUpWOG;IjHwXyp22GE`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Nystatin oral suspension 100IU/ml (24ml Bottle)",
        id: "county__nystatin_oral_suspension_100iuml_24ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/f1SlNJAAxMr`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;f1SlNJAAxMr.QvctQfKAQn3;v424EPiNCAt.n8XlCFUpWOG;zdEZm4Z5KML`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "ORS Co-Pack (4 sachets of low osmolarity ORS (500ml formulation) + 10 tablets of dispersible zinc sulphate tablets 20mg) (Pack)",
        id: "county__ors_co_pack_4_sachets_dispersible_zinc_sulphate_tablets_20mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/vu1eIRte2X7`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;vu1eIRte2X7.QvctQfKAQn3;IXOZKkAxEFu.n8XlCFUpWOG;JTrO9OYowPR`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Oxytocin Injection 10 I.U. (Ampoule)",
        id: "county__oxytocin_injection_10_iu_ampoule",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/PQks88LiY83`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;PQks88LiY83.QvctQfKAQn3;rEQd6IDeXWT.n8XlCFUpWOG;ffP7j9XBixo`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Paracetamol Syrup/Suspension, 120mg/5ml (60ml Bottle)",
        id: "county__paracetamol_syrupsuspension_120mg_5ml_60ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/fssTWMkgFm3`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;fssTWMkgFm3.QvctQfKAQn3;DclammcSWra.n8XlCFUpWOG;tAcjBkf9vqR`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Paracetamol Tablets, 500mg (Tablet)",
        id: "county__paracetamol_tablets_500mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/NKHbkWxRihZ`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;NKHbkWxRihZ.QvctQfKAQn3;l5mDKpIdb3U.n8XlCFUpWOG;MVFnuEjVRIH`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Sodium chloride, 0.9% (isotonic), (500mL bottle) (Bottle)",
        id: "county__sodium_chloride_09_isotonic_500ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/ZkMqBIlB6h4`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;ZkMqBIlB6h4.QvctQfKAQn3;jiOLjNl8eXE.n8XlCFUpWOG;qOKc8iEdsZ8`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Sodium hypochlorite solution 4-6% (5Lt Jar)",
        id: "county__sodium_hypochlorite_solution_4_6_5lt_jar",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/JGcQHMwZP0b`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;JGcQHMwZP0b.QvctQfKAQn3;VwIbS3g8kPG.n8XlCFUpWOG;mLJhBXN6d3m`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Stock status",
        level: "County",
        name: "Tetracycline Eye Ointment,1%, 3.5g tube (Tube)",
        id: "county__tetracycline_eye_ointment1_35g_tube",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/RDb5SFas36A`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;RDb5SFas36A.QvctQfKAQn3;qoEFejcajz1.n8XlCFUpWOG;JRnL0o1E7K8`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: 'Stock status all',
        level: 'County',
        name: 'All commodities',
        id: 'county__all_commodities',
        local_url: `${APP_BASE_URL}/api/county/stockstatus/all`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:SNj7ETKcFO3.QvctQfKAQn3;Rmx1tNUwJyb.QvctQfKAQn3;TjTv4RDUy8A.QvctQfKAQn3;DJC8qxQeJA6.QvctQfKAQn3;G8JcgB3ZHT8.QvctQfKAQn3;Slds2fjm6k5.QvctQfKAQn3;mp0OYo756gW.QvctQfKAQn3;BG8rAWc2pPP.QvctQfKAQn3;C5HRQXl977d.QvctQfKAQn3;lcqBs8Qopdx.QvctQfKAQn3;QqXgC8XD3IF.QvctQfKAQn3;VuGtfH5eHug.QvctQfKAQn3;VJRNI5qVkN1.QvctQfKAQn3;GmDKO6zO1u9.QvctQfKAQn3;f1SlNJAAxMr.QvctQfKAQn3;vu1eIRte2X7.QvctQfKAQn3;PQks88LiY83.QvctQfKAQn3;fssTWMkgFm3.QvctQfKAQn3;NKHbkWxRihZ.QvctQfKAQn3;ZkMqBIlB6h4.QvctQfKAQn3;JGcQHMwZP0b.QvctQfKAQn3;RDb5SFas36A.QvctQfKAQn3;PcX1hwl7aQD.n8XlCFUpWOG;Klw6Oa18M4Y.n8XlCFUpWOG;QGugDSQXwPR.n8XlCFUpWOG;t8vd4GgcRmh.n8XlCFUpWOG;QYT9nPwdqOz.n8XlCFUpWOG;xvX0hsq7F8j.n8XlCFUpWOG;GOFxghdlf5n.n8XlCFUpWOG;BT8vV7Z7anH.n8XlCFUpWOG;Ss60yT7k8lU.n8XlCFUpWOG;WiygygYRqs7.n8XlCFUpWOG;hBItOmE0ybe.n8XlCFUpWOG;WbDKZsPHAOK.n8XlCFUpWOG;mvrXlqZoM0a.n8XlCFUpWOG;v4Ql5RkIJ7M.n8XlCFUpWOG;v424EPiNCAt.n8XlCFUpWOG;IXOZKkAxEFu.n8XlCFUpWOG;rEQd6IDeXWT.n8XlCFUpWOG;DclammcSWra.n8XlCFUpWOG;l5mDKpIdb3U.n8XlCFUpWOG;jiOLjNl8eXE.n8XlCFUpWOG;VwIbS3g8kPG.n8XlCFUpWOG;qoEFejcajz1.n8XlCFUpWOG`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'hfVjCurKxh2',
        default_org_unit_level: '',
        Notes: ''
    },
	{
		page: 'Stock status map',
		level: 'County',
		name: 'All commodities',
		id: 'county__all_commodities_map',
		local_url: `${APP_BASE_URL}/api/county/stockstatus/map`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:jfUzb86mBSP.miM6uIJ2cWx;HwvUHnslwbh.miM6uIJ2cWx;OLYLVMDHEj8.miM6uIJ2cWx;UJeKVZzAnfS.miM6uIJ2cWx;naztfZrbMtd.miM6uIJ2cWx;EtG9ozt2joA.miM6uIJ2cWx;Umi8ZsiqBHw.miM6uIJ2cWx;xZs759QOGvh.miM6uIJ2cWx;HfGVoCZAwtd;nK8sqMAeQHY;ZcngDQJKiEg;wOKbEd8Dbi3;SSARcWY2Ge1;AX1co0SXobM;UUNwkYQhYgX;gEDxkvJmRAm`,
		default_period: 'LAST_MONTH',
		default_org_unit: 'hfVjCurKxh2',
		default_org_unit_level: '',
		Notes: ''
	},
    {
        page: 'Reporting Rate',
        level: 'County',
        name: 'Reporting Rate Trend',
        id: 'county__reporting_rate_trend',
        local_url: `${APP_BASE_URL}/api/county/reportingrate/trend`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;ppdqEN91qZs.REPORTING_RATE_ON_TIME`,
        default_period: 'LAST_12_MONTHS',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 1,
        Notes: ''
    },
    {
        page: 'Reporting Rate',
        level: 'County',
        name: 'Reporting Rate Trend (latest subcounty)',
        id: 'county__latest_reporting_rate_subcounty',
        local_url: `${APP_BASE_URL}/api/county/reportingrate/latesttrend`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 3,
        Notes: ''
    },

    {
        page: 'Reporting Rate',
        level: 'County',
        name: 'Facility Reporting Rate',
        id: 'county__facility_reporting_rate',
        local_url: `${APP_BASE_URL}/api/county/reportingrate/facility`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.ACTUAL_REPORTS;ppdqEN91qZs.EXPECTED_REPORTS`,
        default_period: 'LAST_6_MONTHS',
        default_org_unit: 'vvOK1BxTbet',
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: 'Reporting Rate',
        level: 'County',
        name: 'Subcounty Reporting Rate',
        id: 'county__subcounty_reporting_rate',
        local_url: `${APP_BASE_URL}/api/county/reportingrate/subcounty`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.ACTUAL_REPORTS;ppdqEN91qZs.EXPECTED_REPORTS`,
        default_period: 'LAST_6_MONTHS',
        default_org_unit: 'vvOK1BxTbet',
        default_org_unit_level: 4,
        Notes: ''
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Adrenaline Injection 1mg/ml (Ampoule)",
        id: "county__dq_concordance_adrenaline_injection_1mgml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/SNj7ETKcFO3`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:PcX1hwl7aQD.gcAn4VctXaO;PcX1hwl7aQD.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Albendazole Tab. 400mg (Tablet)",
        id: "county__dq_concordance_albendazole_tab_400mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/Rmx1tNUwJyb`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:Klw6Oa18M4Y.gcAn4VctXaO;Klw6Oa18M4Y.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Amoxicillin Capsules, 500mg (Capsule)",
        id: "county__dq_concordance_amoxicillin_capsules_500mg_capsule",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/TjTv4RDUy8A`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:QGugDSQXwPR.gcAn4VctXaO;QGugDSQXwPR.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Amoxicillin Dispersible Tablets, 250mg (Tablet)",
        id: "county__dq_concordance_amoxicillin_dispersible_tablets_250mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/DJC8qxQeJA6`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:t8vd4GgcRmh.gcAn4VctXaO;t8vd4GgcRmh.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Benzyl penicillin Injection 1 MU (Vial)",
        id: "county__dq_concordance_benzyl_penicillin_injection_1_mu_vial",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/G8JcgB3ZHT8`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:QYT9nPwdqOz.gcAn4VctXaO;QYT9nPwdqOz.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Benzyl penicillin Injection 5 MU (Vial)",
        id: "county__dq_concordance_benzyl_penicillin_injection_5_mu_vial",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/Slds2fjm6k5`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:xvX0hsq7F8j.gcAn4VctXaO;xvX0hsq7F8j.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Chlorhexidine gel, 7.1% (as digluconate) (20 g tube) (Tube)",
        id: "county__dq_concordance_chlorhexidine_gel_71%_as_digluconate_20_g_tube",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/mp0OYo756gW`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:GOFxghdlf5n.gcAn4VctXaO;GOFxghdlf5n.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Gentamicin Injection, 40mg/2ml (Ampoule)",
        id: "county__dq_concordance_gentamicin_injection_40mg2ml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/BG8rAWc2pPP`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:BT8vV7Z7anH.gcAn4VctXaO;BT8vV7Z7anH.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Hydrocortisone Injection 100mg (Vial)",
        id: "county__dq_concordance_hydrocortisone_injection_100mg_vial",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/C5HRQXl977d`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:Ss60yT7k8lU.gcAn4VctXaO;Ss60yT7k8lU.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Insulin, Premix (short acting +intermediate acting) Human [30 regular + 70 NPH) Injection 10ml Bottle (Vial /Bottle)",
        id: "county__dq_concordance_insulin_premix_short_acting_injection_10ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/lcqBs8Qopdx`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:WiygygYRqs7.gcAn4VctXaO;WiygygYRqs7.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Loratadine Tablets, 10mg (Tablet)",
        id: "county__dq_concordance_loratadine_tablets_10mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/QqXgC8XD3IF`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:hBItOmE0ybe.gcAn4VctXaO;hBItOmE0ybe.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Magnesium Sulphate Injection, 500mg/mL (50%), 10mL (Ampoule, 10ml)",
        id: "county__dq_concordance_magnesium_sulphate_injection_500mgml_50%,_10ml_(ampoule,_10ml)",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/VuGtfH5eHug`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:WbDKZsPHAOK.gcAn4VctXaO;WbDKZsPHAOK.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Metronidazole Tablet, 400mg (Tablet)",
        id: "county__dq_concordance_metronidazole_tablet_400mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/VJRNI5qVkN1`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:mvrXlqZoM0a.gcAn4VctXaO;mvrXlqZoM0a.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Midazolam Injection 5mg/ml, 3ml (Ampoule)",
        id: "county__dq_concordance_midazolam_injection_5mgml_3ml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/GmDKO6zO1u9`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:v4Ql5RkIJ7M.gcAn4VctXaO;v4Ql5RkIJ7M.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Nystatin oral suspension 100IU/ml (24ml Bottle)",
        id: "county__dq_concordance_nystatin_oral_suspension_100iuml_24ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/f1SlNJAAxMr`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:v424EPiNCAt.gcAn4VctXaO;v424EPiNCAt.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "ORS Co-Pack (4 sachets of low osmolarity ORS (500ml formulation) + 10 tablets of dispersible zinc sulphate tablets 20mg) (Pack)",
        id: "county__dq_concordance_ors_co_pack_4_sachets_of_low_osmolarity_ors_500ml_formulation_plus_10_tablets_of_dispersible_zinc_sulphate_tablets_20mg",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/vu1eIRte2X7`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:IXOZKkAxEFu.gcAn4VctXaO;IXOZKkAxEFu.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Oxytocin Injection 10 I.U. (Ampoule)",
        id: "county__dq_concordance_oxytocin_injection_10_iu_ampoule",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/PQks88LiY83`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:rEQd6IDeXWT.gcAn4VctXaO;rEQd6IDeXWT.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Paracetamol Syrup/Suspension, 120mg/5ml (60ml Bottle)",
        id: "county__dq_concordance_paracetamol_syrupsuspension_120mg_5ml_60ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/fssTWMkgFm3`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:DclammcSWra.gcAn4VctXaO;DclammcSWra.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Paracetamol Tablets, 500mg (Tablet)",
        id: "county__dq_concordance_paracetamol_tablets_500mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/NKHbkWxRihZ`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:l5mDKpIdb3U.gcAn4VctXaO;l5mDKpIdb3U.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Sodium chloride, 0.9% (isotonic), (500mL bottle) (Bottle)",
        id: "county__dq_concordance_sodium_chloride_09_isotonic_500ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/ZkMqBIlB6h4`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:jiOLjNl8eXE.gcAn4VctXaO;jiOLjNl8eXE.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Sodium hypochlorite solution 4-6% (5Lt Jar)",
        id: "county__dq_concordance_sodium_hypochlorite_solution_4_6_5lt_jar",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/JGcQHMwZP0b`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:VwIbS3g8kPG.gcAn4VctXaO;VwIbS3g8kPG.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "Tetracycline Eye Ointment,1%, 3.5g tube (Tube)",
        id: "county__dq_concordance_tetracycline_eye_ointment1_35g_tube",
        local_url: `${APP_BASE_URL}/api/county/dataquality/concordance/RDb5SFas36A`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:qoEFejcajz1.gcAn4VctXaO;qoEFejcajz1.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Adrenaline Injection 1mg/ml (Ampoule)",
        id: "county__dq_consistency_adrenaline_injection_1mgml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/SNj7ETKcFO3`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:PcX1hwl7aQD.gcAn4VctXaO;PcX1hwl7aQD.QamCa1Dvl7o;PcX1hwl7aQD.g9sZrd25Dvk;PcX1hwl7aQD.hDCmaVTXH7W;PcX1hwl7aQD.Iwcij0NNZNw;PcX1hwl7aQD.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Albendazole Tab. 400mg (Tablet)",
        id: "county__dq_consistency_albendazole_tab_400mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/Rmx1tNUwJyb`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:Klw6Oa18M4Y.gcAn4VctXaO;Klw6Oa18M4Y.QamCa1Dvl7o;Klw6Oa18M4Y.g9sZrd25Dvk;Klw6Oa18M4Y.hDCmaVTXH7W;Klw6Oa18M4Y.Iwcij0NNZNw;Klw6Oa18M4Y.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Amoxicillin Capsules, 500mg (Capsule)",
        id: "county__dq_consistency_amoxicillin_capsules_500mg_capsule",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/TjTv4RDUy8A`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:QGugDSQXwPR.gcAn4VctXaO;QGugDSQXwPR.QamCa1Dvl7o;QGugDSQXwPR.g9sZrd25Dvk;QGugDSQXwPR.hDCmaVTXH7W;QGugDSQXwPR.Iwcij0NNZNw;QGugDSQXwPR.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Amoxicillin Dispersible Tablets, 250mg (Tablet)",
        id: "county__dq_consistency_amoxicillin_dispersible_tablets_250mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/DJC8qxQeJA6`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:t8vd4GgcRmh.gcAn4VctXaO;t8vd4GgcRmh.QamCa1Dvl7o;t8vd4GgcRmh.g9sZrd25Dvk;t8vd4GgcRmh.hDCmaVTXH7W;t8vd4GgcRmh.Iwcij0NNZNw;t8vd4GgcRmh.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Benzyl penicillin Injection 1 MU (Vial)",
        id: "county__dq_consistency_benzyl_penicillin_injection_1_mu_vial",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/G8JcgB3ZHT8`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:QYT9nPwdqOz.gcAn4VctXaO;QYT9nPwdqOz.QamCa1Dvl7o;QYT9nPwdqOz.g9sZrd25Dvk;QYT9nPwdqOz.hDCmaVTXH7W;QYT9nPwdqOz.Iwcij0NNZNw;QYT9nPwdqOz.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Benzyl penicillin Injection 5 MU (Vial)",
        id: "county__dq_consistency_benzyl_penicillin_injection_5_mu_vial",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/Slds2fjm6k5`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:xvX0hsq7F8j.gcAn4VctXaO;xvX0hsq7F8j.QamCa1Dvl7o;xvX0hsq7F8j.g9sZrd25Dvk;xvX0hsq7F8j.hDCmaVTXH7W;xvX0hsq7F8j.Iwcij0NNZNw;xvX0hsq7F8j.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Chlorhexidine gel, 7.1% (as digluconate) (20 g tube) (Tube)",
        id: "county__dq_consistency_chlorhexidine_gel_71_as_digluconate_20_g_tube",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/mp0OYo756gW`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:GOFxghdlf5n.gcAn4VctXaO;GOFxghdlf5n.QamCa1Dvl7o;GOFxghdlf5n.g9sZrd25Dvk;GOFxghdlf5n.hDCmaVTXH7W;GOFxghdlf5n.Iwcij0NNZNw;GOFxghdlf5n.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Gentamicin Injection, 40mg/2ml (Ampoule)",
        id: "county__dq_consistency_gentamicin_injection_40mg2ml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/BG8rAWc2pPP`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:BT8vV7Z7anH.gcAn4VctXaO;BT8vV7Z7anH.QamCa1Dvl7o;BT8vV7Z7anH.g9sZrd25Dvk;BT8vV7Z7anH.hDCmaVTXH7W;BT8vV7Z7anH.Iwcij0NNZNw;BT8vV7Z7anH.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Hydrocortisone Injection 100mg (Vial)",
        id: "county__dq_consistency_hydrocortisone_injection_100mg_vial",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/C5HRQXl977d`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:Ss60yT7k8lU.gcAn4VctXaO;Ss60yT7k8lU.QamCa1Dvl7o;Ss60yT7k8lU.g9sZrd25Dvk;Ss60yT7k8lU.hDCmaVTXH7W;Ss60yT7k8lU.Iwcij0NNZNw;Ss60yT7k8lU.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Insulin, Premix (short acting +intermediate acting) Human [30 regular + 70 NPH) Injection 10ml Bottle (Vial /Bottle)",
        id: "county__dq_consistency_insulin_premix_short_acting_intermediate_acting_human_injection_10ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/lcqBs8Qopdx`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:WiygygYRqs7.gcAn4VctXaO;WiygygYRqs7.QamCa1Dvl7o;WiygygYRqs7.g9sZrd25Dvk;WiygygYRqs7.hDCmaVTXH7W;WiygygYRqs7.Iwcij0NNZNw;WiygygYRqs7.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Loratadine Tablets, 10mg (Tablet)",
        id: "county__dq_consistency_loratadine_tablets_10mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/QqXgC8XD3IF`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:hBItOmE0ybe.gcAn4VctXaO;hBItOmE0ybe.QamCa1Dvl7o;hBItOmE0ybe.g9sZrd25Dvk;hBItOmE0ybe.hDCmaVTXH7W;hBItOmE0ybe.Iwcij0NNZNw;hBItOmE0ybe.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Magnesium Sulphate Injection, 500mg/mL (50%), 10mL (Ampoule, 10ml)",
        id: "county__dq_consistency_magnesium_sulphate_injection_500mgml_50_10ml",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/VuGtfH5eHug`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:WbDKZsPHAOK.gcAn4VctXaO;WbDKZsPHAOK.QamCa1Dvl7o;WbDKZsPHAOK.g9sZrd25Dvk;WbDKZsPHAOK.hDCmaVTXH7W;WbDKZsPHAOK.Iwcij0NNZNw;WbDKZsPHAOK.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Metronidazole Tablet, 400mg (Tablet)",
        id: "county__dq_consistency_metronidazole_tablet_400mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/VJRNI5qVkN1`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:mvrXlqZoM0a.gcAn4VctXaO;mvrXlqZoM0a.QamCa1Dvl7o;mvrXlqZoM0a.g9sZrd25Dvk;mvrXlqZoM0a.hDCmaVTXH7W;mvrXlqZoM0a.Iwcij0NNZNw;mvrXlqZoM0a.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Midazolam Injection 5mg/ml, 3ml (Ampoule)",
        id: "county__dq_consistency_midazolam_injection_5mgml_3ml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/GmDKO6zO1u9`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:v4Ql5RkIJ7M.gcAn4VctXaO;v4Ql5RkIJ7M.QamCa1Dvl7o;v4Ql5RkIJ7M.g9sZrd25Dvk;v4Ql5RkIJ7M.hDCmaVTXH7W;v4Ql5RkIJ7M.Iwcij0NNZNw;v4Ql5RkIJ7M.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Nystatin oral suspension 100IU/ml (24ml Bottle)",
        id: "county__dq_consistency_nystatin_oral_suspension_100iuml_24ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/f1SlNJAAxMr`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:v424EPiNCAt.gcAn4VctXaO;v424EPiNCAt.QamCa1Dvl7o;v424EPiNCAt.g9sZrd25Dvk;v424EPiNCAt.hDCmaVTXH7W;v424EPiNCAt.Iwcij0NNZNw;v424EPiNCAt.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "ORS Co-Pack (4 sachets of low osmolarity ORS (500ml formulation) + 10 tablets of dispersible zinc sulphate tablets 20mg) (Pack)",
        id: "county__dq_consistency_ors_co_pack_4_sachets_of_low_osmolarity_ors_500ml_formulation_plus_10_tablets_of_dispersible_zinc_sulphate_tablets_20mg",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/vu1eIRte2X7`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:IXOZKkAxEFu.gcAn4VctXaO;IXOZKkAxEFu.QamCa1Dvl7o;IXOZKkAxEFu.g9sZrd25Dvk;IXOZKkAxEFu.hDCmaVTXH7W;IXOZKkAxEFu.Iwcij0NNZNw;IXOZKkAxEFu.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Oxytocin Injection 10 I.U. (Ampoule)",
        id: "county__dq_consistency_oxytocin_injection_10_iu_ampoule",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/PQks88LiY83`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:rEQd6IDeXWT.gcAn4VctXaO;rEQd6IDeXWT.QamCa1Dvl7o;rEQd6IDeXWT.g9sZrd25Dvk;rEQd6IDeXWT.hDCmaVTXH7W;rEQd6IDeXWT.Iwcij0NNZNw;rEQd6IDeXWT.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Paracetamol Syrup/Suspension, 120mg/5ml (60ml Bottle)",
        id: "county__dq_consistency_paracetamol_syrupsuspension_120mg_5ml_60ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/fssTWMkgFm3`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:DclammcSWra.gcAn4VctXaO;DclammcSWra.QamCa1Dvl7o;DclammcSWra.g9sZrd25Dvk;DclammcSWra.hDCmaVTXH7W;DclammcSWra.Iwcij0NNZNw;DclammcSWra.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Paracetamol Tablets, 500mg (Tablet)",
        id: "county__dq_consistency_paracetamol_tablets_500mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/NKHbkWxRihZ`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:l5mDKpIdb3U.gcAn4VctXaO;l5mDKpIdb3U.QamCa1Dvl7o;l5mDKpIdb3U.g9sZrd25Dvk;l5mDKpIdb3U.hDCmaVTXH7W;l5mDKpIdb3U.Iwcij0NNZNw;l5mDKpIdb3U.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Sodium chloride, 0.9% (isotonic), (500mL bottle) (Bottle)",
        id: "county__dq_consistency_sodium_chloride_09%_isotonic_500ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/ZkMqBIlB6h4`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:jiOLjNl8eXE.gcAn4VctXaO;jiOLjNl8eXE.QamCa1Dvl7o;jiOLjNl8eXE.g9sZrd25Dvk;jiOLjNl8eXE.hDCmaVTXH7W;jiOLjNl8eXE.Iwcij0NNZNw;jiOLjNl8eXE.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Sodium hypochlorite solution 4-6% (5Lt Jar)",
        id: "county__dq_consistency_sodium_hypochlorite_solution_4_6_5lt_jar",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/JGcQHMwZP0b`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:VwIbS3g8kPG.gcAn4VctXaO;VwIbS3g8kPG.QamCa1Dvl7o;VwIbS3g8kPG.g9sZrd25Dvk;VwIbS3g8kPG.hDCmaVTXH7W;VwIbS3g8kPG.Iwcij0NNZNw;VwIbS3g8kPG.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "Tetracycline Eye Ointment,1%, 3.5g tube (Tube)",
        id: "county__dq_consistency_tetracycline_eye_ointment1_35g_tube",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/RDb5SFas36A`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:qoEFejcajz1.gcAn4VctXaO;qoEFejcajz1.QamCa1Dvl7o;qoEFejcajz1.g9sZrd25Dvk;qoEFejcajz1.hDCmaVTXH7W;qoEFejcajz1.Iwcij0NNZNw;qoEFejcajz1.n8XlCFUpWOG`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_level: 5,
        notes: ""
    },
    {
        page: 'Supply Chain Performance Summary',
        level: 'County',
        name: 'Indicator Summary',
        id: 'county__indicator_summary',
        local_url: `${APP_BASE_URL}/api/county/supplychain/indicatorsummary`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ppdqEN91qZs.REPORTING_RATE;ppdqEN91qZs.REPORTING_RATE_ON_TIME;SFwHgXxyaBX;uHSqkMzQWbJ;m2Dxu9fe9Ps;VA3KZphR8Dc;h1NaQphYTFv;rdUP34gG5z7;gkY7xYvyV01;snkYSLUGXk6;tFikgcVkTSr;n8B0vvf1PCW;aAHIH8QcdoF;P9PNWcxgAHG;QkKle90Kwfs;IjHwXyp22GE;zdEZm4Z5KML;JTrO9OYowPR;ffP7j9XBixo;tAcjBkf9vqR;MVFnuEjVRIH;qOKc8iEdsZ8;mLJhBXN6d3m;JRnL0o1E7K8`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 5,
        Notes: ''
    },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'Combined Oral Contraceptive Pills',
    //     id: 'county__indicator_trends_cocp',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/hH9gmEmEhH4`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:hH9gmEmEhH4`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'Progestin Only Pills',
    //     id: 'county__indicator_trends_pop',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/dl4JcBnxu0X`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:dl4JcBnxu0X`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'Emergency Contraceptive Pills',
    //     id: 'county__indicator_trends_ecp',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/qaBPR9wbWku`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:qaBPR9wbWku`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'Cycle Beads',
    //     id: 'county__indicator_trends_cb',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/bGGT0F7iRxt`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:bGGT0F7iRxt`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'Injectables',
    //     id: 'county__indicator_trends_inj',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/J6qnTev1LXw`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:J6qnTev1LXw`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'IUCDs',
    //     id: 'county__indicator_trends_iucd',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/tfPZ6sGgh4q`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:tfPZ6sGgh4q`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'Implants (1 rod)',
    //     id: 'county__indicator_trends_i1r',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/XgJfT71Unkn`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:XgJfT71Unkn`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'Implants (2 rod)',
    //     id: 'county__indicator_trends_i2r',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/MsS41X1GEFr`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:MsS41X1GEFr`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'Female Condoms',
    //     id: 'county__indicator_trends_fcd',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/AR7RhdC90IV`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:AR7RhdC90IV`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'Male Condoms',
    //     id: 'county__indicator_trends_mcd',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/AVDzuypqGt9`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:AVDzuypqGt9`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    // {
    //     page: 'Supply Chain Performance Trends',
    //     level: 'County',
    //     name: 'Others',
    //     id: 'county__indicator_trends_other',
    //     local_url: `${APP_BASE_URL}/api/county/supplychain/indicatortrends/QKvDccYJ18W`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:QKvDccYJ18W`,
    //     default_period: 'LAST_6_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 5,
    //     Notes: ''
    // },
    {
        page: 'Accountability',
        level: 'County',
        name: 'Accountability',
        id: 'county__accountability',
        local_url: `${APP_BASE_URL}/api/county/accountability`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:PcX1hwl7aQD.gcAn4VctXaO;Klw6Oa18M4Y.gcAn4VctXaO;QGugDSQXwPR.gcAn4VctXaO;t8vd4GgcRmh.gcAn4VctXaO;QYT9nPwdqOz.gcAn4VctXaO;xvX0hsq7F8j.gcAn4VctXaO;GOFxghdlf5n.gcAn4VctXaO;BT8vV7Z7anH.gcAn4VctXaO;Ss60yT7k8lU.gcAn4VctXaO;WiygygYRqs7.gcAn4VctXaO;hBItOmE0ybe.gcAn4VctXaO;WbDKZsPHAOK.gcAn4VctXaO;mvrXlqZoM0a.gcAn4VctXaO;v4Ql5RkIJ7M.gcAn4VctXaO;v424EPiNCAt.gcAn4VctXaO;IXOZKkAxEFu.gcAn4VctXaO;rEQd6IDeXWT.gcAn4VctXaO;DclammcSWra.gcAn4VctXaO;l5mDKpIdb3U.gcAn4VctXaO;jiOLjNl8eXE.gcAn4VctXaO;VwIbS3g8kPG.gcAn4VctXaO;qoEFejcajz1.gcAn4VctXaO;PcX1hwl7aQD.g9sZrd25Dvk;Klw6Oa18M4Y.g9sZrd25Dvk;QGugDSQXwPR.g9sZrd25Dvk;t8vd4GgcRmh.g9sZrd25Dvk;QYT9nPwdqOz.g9sZrd25Dvk;xvX0hsq7F8j.g9sZrd25Dvk;GOFxghdlf5n.g9sZrd25Dvk;BT8vV7Z7anH.g9sZrd25Dvk;Ss60yT7k8lU.g9sZrd25Dvk;WiygygYRqs7.g9sZrd25Dvk;hBItOmE0ybe.g9sZrd25Dvk;WbDKZsPHAOK.g9sZrd25Dvk;mvrXlqZoM0a.g9sZrd25Dvk;v4Ql5RkIJ7M.g9sZrd25Dvk;v424EPiNCAt.g9sZrd25Dvk;IXOZKkAxEFu.g9sZrd25Dvk;rEQd6IDeXWT.g9sZrd25Dvk;DclammcSWra.g9sZrd25Dvk;l5mDKpIdb3U.g9sZrd25Dvk;jiOLjNl8eXE.g9sZrd25Dvk;VwIbS3g8kPG.g9sZrd25Dvk;qoEFejcajz1.g9sZrd25Dvk;PcX1hwl7aQD.QamCa1Dvl7o;Klw6Oa18M4Y.QamCa1Dvl7o;QGugDSQXwPR.QamCa1Dvl7o;t8vd4GgcRmh.QamCa1Dvl7o;QYT9nPwdqOz.QamCa1Dvl7o;xvX0hsq7F8j.QamCa1Dvl7o;GOFxghdlf5n.QamCa1Dvl7o;BT8vV7Z7anH.QamCa1Dvl7o;Ss60yT7k8lU.QamCa1Dvl7o;WiygygYRqs7.QamCa1Dvl7o;hBItOmE0ybe.QamCa1Dvl7o;WbDKZsPHAOK.QamCa1Dvl7o;mvrXlqZoM0a.QamCa1Dvl7o;v4Ql5RkIJ7M.QamCa1Dvl7o;v424EPiNCAt.QamCa1Dvl7o;IXOZKkAxEFu.QamCa1Dvl7o;rEQd6IDeXWT.QamCa1Dvl7o;DclammcSWra.QamCa1Dvl7o;l5mDKpIdb3U.QamCa1Dvl7o;jiOLjNl8eXE.QamCa1Dvl7o;VwIbS3g8kPG.QamCa1Dvl7o;qoEFejcajz1.QamCa1Dvl7o;PcX1hwl7aQD.hDCmaVTXH7W;Klw6Oa18M4Y.hDCmaVTXH7W;QGugDSQXwPR.hDCmaVTXH7W;t8vd4GgcRmh.hDCmaVTXH7W;QYT9nPwdqOz.hDCmaVTXH7W;xvX0hsq7F8j.hDCmaVTXH7W;GOFxghdlf5n.hDCmaVTXH7W;BT8vV7Z7anH.hDCmaVTXH7W;Ss60yT7k8lU.hDCmaVTXH7W;WiygygYRqs7.hDCmaVTXH7W;hBItOmE0ybe.hDCmaVTXH7W;WbDKZsPHAOK.hDCmaVTXH7W;mvrXlqZoM0a.hDCmaVTXH7W;v4Ql5RkIJ7M.hDCmaVTXH7W;v424EPiNCAt.hDCmaVTXH7W;IXOZKkAxEFu.hDCmaVTXH7W;rEQd6IDeXWT.hDCmaVTXH7W;DclammcSWra.hDCmaVTXH7W;l5mDKpIdb3U.hDCmaVTXH7W;jiOLjNl8eXE.hDCmaVTXH7W;VwIbS3g8kPG.hDCmaVTXH7W;qoEFejcajz1.hDCmaVTXH7W;PcX1hwl7aQD.Iwcij0NNZNw;Klw6Oa18M4Y.Iwcij0NNZNw;QGugDSQXwPR.Iwcij0NNZNw;t8vd4GgcRmh.Iwcij0NNZNw;QYT9nPwdqOz.Iwcij0NNZNw;xvX0hsq7F8j.Iwcij0NNZNw;GOFxghdlf5n.Iwcij0NNZNw;BT8vV7Z7anH.Iwcij0NNZNw;Ss60yT7k8lU.Iwcij0NNZNw;WiygygYRqs7.Iwcij0NNZNw;hBItOmE0ybe.Iwcij0NNZNw;WbDKZsPHAOK.Iwcij0NNZNw;mvrXlqZoM0a.Iwcij0NNZNw;v4Ql5RkIJ7M.Iwcij0NNZNw;v424EPiNCAt.Iwcij0NNZNw;IXOZKkAxEFu.Iwcij0NNZNw;rEQd6IDeXWT.Iwcij0NNZNw;DclammcSWra.Iwcij0NNZNw;l5mDKpIdb3U.Iwcij0NNZNw;jiOLjNl8eXE.Iwcij0NNZNw;VwIbS3g8kPG.Iwcij0NNZNw;qoEFejcajz1.Iwcij0NNZNw;PcX1hwl7aQD.n8XlCFUpWOG;Klw6Oa18M4Y.n8XlCFUpWOG;QGugDSQXwPR.n8XlCFUpWOG;t8vd4GgcRmh.n8XlCFUpWOG;QYT9nPwdqOz.n8XlCFUpWOG;xvX0hsq7F8j.n8XlCFUpWOG;GOFxghdlf5n.n8XlCFUpWOG;BT8vV7Z7anH.n8XlCFUpWOG;Ss60yT7k8lU.n8XlCFUpWOG;WiygygYRqs7.n8XlCFUpWOG;hBItOmE0ybe.n8XlCFUpWOG;WbDKZsPHAOK.n8XlCFUpWOG;mvrXlqZoM0a.n8XlCFUpWOG;v4Ql5RkIJ7M.n8XlCFUpWOG;v424EPiNCAt.n8XlCFUpWOG;IXOZKkAxEFu.n8XlCFUpWOG;rEQd6IDeXWT.n8XlCFUpWOG;DclammcSWra.n8XlCFUpWOG;l5mDKpIdb3U.n8XlCFUpWOG;jiOLjNl8eXE.n8XlCFUpWOG;VwIbS3g8kPG.n8XlCFUpWOG;qoEFejcajz1.n8XlCFUpWOG`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 1,
        Notes: ''
    },
    {
        page: 'Expiries',
        level: 'County',
        name: 'Expiries',
        id: 'county__expiries',
        local_url: `${APP_BASE_URL}/api/county/expiries`,
        //local_url: 'https://api.jsonbin.io/v3/qs/6364c99b0e6a79321e3edcf0',PbQbHXJ1Cxz
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:PcX1hwl7aQD.PbQbHXJ1Cxz;Klw6Oa18M4Y.PbQbHXJ1Cxz;QGugDSQXwPR.PbQbHXJ1Cxz;t8vd4GgcRmh.PbQbHXJ1Cxz;QYT9nPwdqOz.PbQbHXJ1Cxz;xvX0hsq7F8j.PbQbHXJ1Cxz;GOFxghdlf5n.PbQbHXJ1Cxz;BT8vV7Z7anH.PbQbHXJ1Cxz;Ss60yT7k8lU.PbQbHXJ1Cxz;WiygygYRqs7.PbQbHXJ1Cxz;hBItOmE0ybe.PbQbHXJ1Cxz;WbDKZsPHAOK.PbQbHXJ1Cxz;mvrXlqZoM0a.PbQbHXJ1Cxz;v4Ql5RkIJ7M.PbQbHXJ1Cxz;v424EPiNCAt.PbQbHXJ1Cxz;IXOZKkAxEFu.PbQbHXJ1Cxz;rEQd6IDeXWT.PbQbHXJ1Cxz;DclammcSWra.PbQbHXJ1Cxz;l5mDKpIdb3U.PbQbHXJ1Cxz;jiOLjNl8eXE.PbQbHXJ1Cxz;VwIbS3g8kPG.PbQbHXJ1Cxz;qoEFejcajz1.PbQbHXJ1Cxz;SNj7ETKcFO3.QvctQfKAQn3;Rmx1tNUwJyb.QvctQfKAQn3;TjTv4RDUy8A.QvctQfKAQn3;DJC8qxQeJA6.QvctQfKAQn3;G8JcgB3ZHT8.QvctQfKAQn3;Slds2fjm6k5.QvctQfKAQn3;mp0OYo756gW.QvctQfKAQn3;BG8rAWc2pPP.QvctQfKAQn3;C5HRQXl977d.QvctQfKAQn3;lcqBs8Qopdx.QvctQfKAQn3;QqXgC8XD3IF.QvctQfKAQn3;VuGtfH5eHug.QvctQfKAQn3;VJRNI5qVkN1.QvctQfKAQn3;GmDKO6zO1u9.QvctQfKAQn3;f1SlNJAAxMr.QvctQfKAQn3;vu1eIRte2X7.QvctQfKAQn3;PQks88LiY83.QvctQfKAQn3;fssTWMkgFm3.QvctQfKAQn3;NKHbkWxRihZ.QvctQfKAQn3;ZkMqBIlB6h4.QvctQfKAQn3;JGcQHMwZP0b.QvctQfKAQn3;RDb5SFas36A.QvctQfKAQn3`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 1,
        Notes: ''
    },
    // {
    //     page: 'Issues vs Receipts',
    //     level: 'County',
    //     name: 'Issues vs Receipts',
    //     id: 'county__issues_vs_receipts',
    //     local_url: `${APP_BASE_URL}/api/county/issuesvsreceipts`,
    //     url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:m1U1MJZoK9Q.DTnItSklSr8;CxoGtEwF44m.DTnItSklSr8;nGR47qCgOfQ.DTnItSklSr8;RXJmB0afFhv.DTnItSklSr8;ri9reJBhA2Y.DTnItSklSr8;QZpWVTFZEE7.DTnItSklSr8;WLS1R40DxXt.DTnItSklSr8;CH3syaQ3wJ3.DTnItSklSr8;YSjqRqkkQdi.DTnItSklSr8;uiU7PDbqn74.DTnItSklSr8;FyLIhJocwlR.DTnItSklSr8;hH9gmEmEhH4.VW51Ep3auXR;bGGT0F7iRxt.VW51Ep3auXR;qaBPR9wbWku.VW51Ep3auXR;AR7RhdC90IV.VW51Ep3auXR;tfPZ6sGgh4q.VW51Ep3auXR;XgJfT71Unkn.VW51Ep3auXR;MsS41X1GEFr.VW51Ep3auXR;J6qnTev1LXw.VW51Ep3auXR;AVDzuypqGt9.VW51Ep3auXR;dl4JcBnxu0X.VW51Ep3auXR;QKvDccYJ18W.VW51Ep3auXR`,
    //     default_period: 'LAST_3_MONTHS',
    //     default_org_unit: 'HfVjCurKxh2',
    //     default_org_unit_level: 1,
    //     Notes: ''
    // },

    {
        page: "Health Facility Followup",
        level: "County",
        name: "Adrenaline Injection 1mg/ml (Ampoule)",
        id: "county__facilities_followup_adrenaline_injection_1mgml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/SNj7ETKcFO3`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:SFwHgXxyaBX;PcX1hwl7aQD.n8XlCFUpWOG;SNj7ETKcFO3.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Albendazole Tab. 400mg (Tablet)",
        id: "county__facilities_followup_albendazole_tab_400mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/Rmx1tNUwJyb`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:uHSqkMzQWbJ;Klw6Oa18M4Y.n8XlCFUpWOG;Rmx1tNUwJyb.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Amoxicillin Capsules, 500mg (Capsule)",
        id: "county__facilities_followup_amoxicillin_capsules_500mg_capsule",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/TjTv4RDUy8A`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:m2Dxu9fe9Ps;QGugDSQXwPR.n8XlCFUpWOG;TjTv4RDUy8A.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Amoxicillin Dispersible Tablets, 250mg (Tablet)",
        id: "county__facilities_followup_amoxicillin_dispersible_tablets_250mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/DJC8qxQeJA6`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:VA3KZphR8Dc;t8vd4GgcRmh.n8XlCFUpWOG;DJC8qxQeJA6.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Benzyl penicillin Injection 1 MU (Vial)",
        id: "county__facilities_followup_benzyl_penicillin_injection_1_mu_vial",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/G8JcgB3ZHT8`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:h1NaQphYTFv;QYT9nPwdqOz.n8XlCFUpWOG;G8JcgB3ZHT8.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Benzyl penicillin Injection 5 MU (Vial)",
        id: "county__facilities_followup_benzyl_penicillin_injection_5_mu_vial",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/Slds2fjm6k5`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:rdUP34gG5z7;xvX0hsq7F8j.n8XlCFUpWOG;Slds2fjm6k5.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Chlorhexidine gel, 7.1% (as digluconate) (20 g tube) (Tube)",
        id: "county__facilities_followup_chlorhexidine_gel_71_as_digluconate_20g_tube",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/mp0OYo756gW`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:gkY7xYvyV01;GOFxghdlf5n.n8XlCFUpWOG;mp0OYo756gW.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Gentamicin Injection, 40mg/2ml (Ampoule)",
        id: "county__facilities_followup_gentamicin_injection_40mg2ml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/BG8rAWc2pPP`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:snkYSLUGXk6;BT8vV7Z7anH.n8XlCFUpWOG;BG8rAWc2pPP.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Hydrocortisone Injection 100mg (Vial)",
        id: "county__facilities_followup_hydrocortisone_injection_100mg_vial",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/C5HRQXl977d`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:tFikgcVkTSr;Ss60yT7k8lU.n8XlCFUpWOG;C5HRQXl977d.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Insulin, Premix (short acting +intermediate acting) Human [30 regular + 70 NPH) Injection 10ml Bottle (Vial /Bottle)",
        id: "county__facilities_followup_insulin_premix_short_acting_injection_10ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/lcqBs8Qopdx`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:n8B0vvf1PCW;WiygygYRqs7.n8XlCFUpWOG;lcqBs8Qopdx.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Loratadine Tablets, 10mg (Tablet)",
        id: "county__facilities_followup_loratadine_tablets_10mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/QqXgC8XD3IF`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:aAHIH8QcdoF;hBItOmE0ybe.n8XlCFUpWOG;QqXgC8XD3IF.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Magnesium Sulphate Injection, 500mg/mL (50%), 10mL (Ampoule, 10ml)",
        id: "county__facilities_followup_magnesium_sulphate_injection_500mgml_50_10ml",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/VuGtfH5eHug`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:P9PNWcxgAHG;WbDKZsPHAOK.n8XlCFUpWOG;VuGtfH5eHug.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Metronidazole Tablet, 400mg (Tablet)",
        id: "county__facilities_followup_metronidazole_tablet_400mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/VJRNI5qVkN1`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:QkKle90Kwfs;mvrXlqZoM0a.n8XlCFUpWOG;VJRNI5qVkN1.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Midazolam Injection 5mg/ml, 3ml (Ampoule)",
        id: "county__facilities_followup_midazolam_injection_5mgml_3ml_ampoule",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/GmDKO6zO1u9`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:IjHwXyp22GE;v4Ql5RkIJ7M.n8XlCFUpWOG;GmDKO6zO1u9.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Nystatin oral suspension 100IU/ml (24ml Bottle)",
        id: "county__facilities_followup_nystatin_oral_suspension_100iuml_24ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/f1SlNJAAxMr`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:zdEZm4Z5KML;v424EPiNCAt.n8XlCFUpWOG;f1SlNJAAxMr.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "ORS Co-Pack (4 sachets of low osmolarity ORS (500ml formulation) + 10 tablets of dispersible zinc sulphate tablets 20mg) (Pack)",
        id: "county__facilities_followup_ors_co_pack_4_sachets_of_low_osmolarity_ors_500ml_formulation",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/vu1eIRte2X7`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:JTrO9OYowPR;IXOZKkAxEFu.n8XlCFUpWOG;vu1eIRte2X7.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Oxytocin Injection 10 I.U. (Ampoule)",
        id: "county__facilities_followup_oxytocin_injection_10_iu_ampoule",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/PQks88LiY83`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ffP7j9XBixo;rEQd6IDeXWT.n8XlCFUpWOG;PQks88LiY83.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Paracetamol Syrup/Suspension, 120mg/5ml (60ml Bottle)",
        id: "county__facilities_followup_paracetamol_syrupsuspension_120mg_5ml_60ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/fssTWMkgFm3`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:tAcjBkf9vqR;DclammcSWra.n8XlCFUpWOG;fssTWMkgFm3.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Paracetamol Tablets, 500mg (Tablet)",
        id: "county__facilities_followup_paracetamol_tablets_500mg_tablet",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/NKHbkWxRihZ`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:MVFnuEjVRIH;l5mDKpIdb3U.n8XlCFUpWOG;NKHbkWxRihZ.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Sodium chloride, 0.9% (isotonic), (500mL bottle) (Bottle)",
        id: "county__facilities_followup_sodium_chloride_09_isotonic_500ml_bottle",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/ZkMqBIlB6h4`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:qOKc8iEdsZ8;jiOLjNl8eXE.n8XlCFUpWOG;ZkMqBIlB6h4.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Sodium hypochlorite solution 4-6% (5Lt Jar)",
        id: "county__facilities_followup_sodium_hypochlorite_solution_4_6_5lt_jar",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/JGcQHMwZP0b`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:mLJhBXN6d3m;VwIbS3g8kPG.n8XlCFUpWOG;JGcQHMwZP0b.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Health Facility Followup",
        level: "County",
        name: "Tetracycline Eye Ointment,1%, 3.5g tube (Tube)",
        id: "county__facilities_followup_tetracycline_eye_ointment1_35g_tube_tube",
        local_url: `${APP_BASE_URL}/api/county/hffollowup/understocked/RDb5SFas36A`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:JRnL0o1E7K8;qoEFejcajz1.n8XlCFUpWOG;RDb5SFas36A.QvctQfKAQn3`,
        default_period: "LAST_6_MONTHS",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },

    {
        page: 'National Stocks',
        level: 'National',
        name: 'National Summary',
        id: 'national__summary_facility_mos',
        local_url: `${APP_BASE_URL}/api/national/summary/facility-mos`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:HfGVoCZAwtd;ZcngDQJKiEg;nK8sqMAeQHY;wOKbEd8Dbi3;SSARcWY2Ge1;AX1co0SXobM;UUNwkYQhYgX;gEDxkvJmRAm`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: '',
        Notes: ''
      },
      {
        page: 'National Stocks',
        level: 'National',
        name: 'National Summary',
        id: 'national__summary_pending_mos',
        local_url: `${APP_BASE_URL}/api/national/summary/pending-mos`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:E8WZg2xUe6D;LzIEVzUpWIG;UW54RautAEK;V00M1X2mgCp;Rf9K17Q8KA5;ELorMg0kQhA;W1VReF5uwnI;W1VReF5uwnI`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: '',
        Notes: ''
      },
      {
        page: 'National Stocks',
        level: 'National',
        name: 'National Summary',
        id: 'national__summary_kemsa_mos',
        local_url: `${APP_BASE_URL}/api/national/summary/kemsa-mos`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:A3hCPRmBEc1;VJjIApOdBDM;xifzJdZepGL;m5JchlPXYGh;AcHIhCDHQ5q;ImjyH2PKcrb;MqaP08m7qpB;TaF3YvKkHvw`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: '',
        Notes: ''
      },	
      {
        page: 'National Stocks',
        level: 'National',
        name: 'National Stocks',
        id: 'national__kemsa_summary',
        local_url: `${APP_BASE_URL}/api/national/summary/kemsasummary`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:Aui7lNDOsSF.svPoNZ3VkVx;Aui7lNDOsSF.G3eMNWySdZq;Aui7lNDOsSF.Q9rPivWnD4K;Aui7lNDOsSF.HMTuusGLTUj;Aui7lNDOsSF.sEiFVVjqcfg;Kkh8ZtRWFmX.svPoNZ3VkVx;Kkh8ZtRWFmX.G3eMNWySdZq;Kkh8ZtRWFmX.Q9rPivWnD4K;Kkh8ZtRWFmX.HMTuusGLTUj;Kkh8ZtRWFmX.sEiFVVjqcfg;iZe9QHpC31Y.svPoNZ3VkVx;iZe9QHpC31Y.G3eMNWySdZq;iZe9QHpC31Y.Q9rPivWnD4K;iZe9QHpC31Y.HMTuusGLTUj;iZe9QHpC31Y.sEiFVVjqcfg;E7M967QxxFc.svPoNZ3VkVx;E7M967QxxFc.G3eMNWySdZq;E7M967QxxFc.Q9rPivWnD4K;E7M967QxxFc.HMTuusGLTUj;E7M967QxxFc.sEiFVVjqcfg;Wupc6TOJhcK.svPoNZ3VkVx;Wupc6TOJhcK.G3eMNWySdZq;Wupc6TOJhcK.Q9rPivWnD4K;Wupc6TOJhcK.HMTuusGLTUj;Wupc6TOJhcK.sEiFVVjqcfg;lZCba7Ijb7x.svPoNZ3VkVx;lZCba7Ijb7x.G3eMNWySdZq;lZCba7Ijb7x.Q9rPivWnD4K;lZCba7Ijb7x.HMTuusGLTUj;lZCba7Ijb7x.sEiFVVjqcfg;ALnonKSyDct.svPoNZ3VkVx;ALnonKSyDct.G3eMNWySdZq;ALnonKSyDct.Q9rPivWnD4K;ALnonKSyDct.HMTuusGLTUj;ALnonKSyDct.sEiFVVjqcfg;ZiLVFNkjwdB.svPoNZ3VkVx;ZiLVFNkjwdB.G3eMNWySdZq;ZiLVFNkjwdB.Q9rPivWnD4K;ZiLVFNkjwdB.HMTuusGLTUj;ZiLVFNkjwdB.sEiFVVjqcfg`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: '',
        Notes: ''
      },
      {
        page: 'National SOH Comparison',
        level: 'National',
        name: 'SOH Comparison',
        id: 'national__soh_comparison',
        local_url: `${APP_BASE_URL}/api/national/sohcomparison`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:jfUzb86mBSP.miM6uIJ2cWx;HwvUHnslwbh.miM6uIJ2cWx;OLYLVMDHEj8.miM6uIJ2cWx;UJeKVZzAnfS.miM6uIJ2cWx;naztfZrbMtd.miM6uIJ2cWx;EtG9ozt2joA.miM6uIJ2cWx;Umi8ZsiqBHw.miM6uIJ2cWx;xZs759QOGvh.miM6uIJ2cWx;Aui7lNDOsSF.HMTuusGLTUj;iZe9QHpC31Y.HMTuusGLTUj;Kkh8ZtRWFmX.HMTuusGLTUj;E7M967QxxFc.HMTuusGLTUj;Wupc6TOJhcK.HMTuusGLTUj;lZCba7Ijb7x.HMTuusGLTUj;ALnonKSyDct.HMTuusGLTUj;ZiLVFNkjwdB.HMTuusGLTUj;BnGDrFwyQp9.rPAsF4cpNxm;c0MB4RmVjxk.rPAsF4cpNxm;qnZmg5tNSMy.rPAsF4cpNxm;gVp1KSFI69G.rPAsF4cpNxm;iOARK31NdLp.rPAsF4cpNxm;imheYfA1Kiw.rPAsF4cpNxm;cPlWFYbBacW.rPAsF4cpNxm;f0AIAR5pJ2F.rPAsF4cpNxm`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: '',
        Notes: ''
      },
    //   {
    //     page: 'Pending Shipments',
    //     level: 'National',
    //     name: 'Pending Shipments',
    //     id: 'national__pending_shipments',
    //     local_url: `${APP_BASE_URL}/api/national/pendingshipment`,
    //     url: `${DHIS_BASE_API_URL}/dataStore/pending/stocks`,
    //     default_period: '',
    //     default_org_unit: '',
    //     default_org_unit_level: '',
    //     Notes: ''
    //   },
      {
        page: 'Issues vs Receipts',
        level: 'National',
        name: 'Issues vs Receipts',
        id: 'national__issues_vs_receipts',
        local_url: `${APP_BASE_URL}/api/national/issuesvsreceipts`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:jfUzb86mBSP.DTnItSklSr8;HwvUHnslwbh.DTnItSklSr8;OLYLVMDHEj8.DTnItSklSr8;UJeKVZzAnfS.DTnItSklSr8;naztfZrbMtd.DTnItSklSr8;EtG9ozt2joA.DTnItSklSr8;Umi8ZsiqBHw.DTnItSklSr8;BnGDrFwyQp9.yuvCdaFqdCW;c0MB4RmVjxk.yuvCdaFqdCW;qnZmg5tNSMy.yuvCdaFqdCW;gVp1KSFI69G.yuvCdaFqdCW;iOARK31NdLp.yuvCdaFqdCW;imheYfA1Kiw.yuvCdaFqdCW;eFqDcjgvt39.EJ8nUfcupBq`,
        default_period: 'LAST_3_MONTHS',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: '',
        Notes: ''
      }
];

module.exports = emms;
