let DHIS_BASE_API_URL = process.env.REACT_APP_DHIS_BASE_API_URL;
let APP_BASE_URL =
  process.env.REACT_APP_APP_BASE_URL || 'http://41.89.94.99:3000';
let fp = [
	{
	  "Page": "Global",
	  "Level": "All",
	  "Name": "Counties list",
	  "ID": "all__counties_list",
	  "URLs": "https://hiskenya.org/api/organisationUnits.json?filter=level:eq:2&fields=id,name,level&paging=false",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Global",
	  "Level": "All",
	  "Name": "Subcounties list",
	  "ID": "all__subcounties_list",
	  "URLs": "https://hiskenya.org/api/organisationUnits.json?filter=level:eq:3&fields=id,name,level,parent&paging=false",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Global",
	  "Level": "All",
	  "Name": "Wards list",
	  "ID": "all__wards_list",
	  "URLs": "https://hiskenya.org/api/organisationUnits.json?filter=level:eq:4&fields=id,name,level,parent&paging=false",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Global",
	  "Level": "All",
	  "Name": "Facilities list",
	  "ID": "all__facilities_list",
	  "URLs": "https://hiskenya.org/api/organisationUnits.json?filter=level:eq:5&fields=id,name,level,parent&paging=false",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Global",
	  "Level": "All",
	  "Name": "CUs list",
	  "ID": "all__cus_list",
	  "URLs": "https://hiskenya.org/api/organisationUnits.json?filter=level:eq:6&fields=id,name,level,parent&paging=false",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Global",
	  "Level": "All",
	  "Name": "MFL codes",
	  "ID": "all__mfl_codes",
	  "URLs": "https://hiskenya.org/api/organisationUnits.json?fields=id,code&paging=false",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Global",
	  "Level": "All",
	  "Name": "User details",
	  "ID": "all__user_details",
	  "URLs": "https://hiskenya.org/api/me.json",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Global",
	  "Level": "All",
	  "Name": "FP Commodities",
	  "ID": "all__commodities",
	  "URLs": "https://hiskenya.org/api/dataSets/g3RQRuh8ikd.json?fields=dataSetElements[dataElement[id,name]]",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "",
	  "Level": "",
	  "Name": "",
	  "ID": "",
	  "URLs": "",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Dashboard",
	  "Level": "All",
	  "Name": "Stock Status",
	  "ID": "all__stock_status",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:m1U1MJZoK9Q.QvctQfKAQn3;uiU7PDbqn74.QvctQfKAQn3;nGR47qCgOfQ.QvctQfKAQn3;CxoGtEwF44m.QvctQfKAQn3;CH3syaQ3wJ3.QvctQfKAQn3;ri9reJBhA2Y.QvctQfKAQn3;QZpWVTFZEE7.QvctQfKAQn3;WLS1R40DxXt.QvctQfKAQn3;RXJmB0afFhv.QvctQfKAQn3;YSjqRqkkQdi.QvctQfKAQn3;FyLIhJocwlR.QvctQfKAQn3;hH9gmEmEhH4.i9dqmLZr7fd;dl4JcBnxu0X.i9dqmLZr7fd;qaBPR9wbWku.i9dqmLZr7fd;bGGT0F7iRxt.i9dqmLZr7fd;J6qnTev1LXw.i9dqmLZr7fd;tfPZ6sGgh4q.i9dqmLZr7fd;XgJfT71Unkn.i9dqmLZr7fd;MsS41X1GEFr.i9dqmLZr7fd;AR7RhdC90IV.i9dqmLZr7fd;AVDzuypqGt9.i9dqmLZr7fd;QKvDccYJ18W.i9dqmLZr7fd;vBtxrMus3Qf;H7CkBPdObiC;KWavo9MWGBT;E5ehG5Qmk5Y;xvxsOVLQWqh;HP1u3rO8rM7;ZbLcoTanQnP;Zz6gJ3FAKjr;z5rdAD1Z9rH;DWMK6mvF9LH;VHtSG6l59rb",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Dashboard",
	  "Level": "All",
	  "Name": "MOS by commodity",
	  "ID": "all__mos_by_commodity",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:vBtxrMus3Qf;H7CkBPdObiC;KWavo9MWGBT;HP1u3rO8rM7;E5ehG5Qmk5Y;ZbLcoTanQnP;Zz6gJ3FAKjr;xvxsOVLQWqh;z5rdAD1Z9rH;DWMK6mvF9LH;VHtSG6l59rb",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Dashboard",
	  "Level": "All",
	  "Name": "Facilities stock status (count)",
	  "ID": "all__facilities_stock_status",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:vBtxrMus3Qf;H7CkBPdObiC;KWavo9MWGBT;HP1u3rO8rM7;E5ehG5Qmk5Y;ZbLcoTanQnP;Zz6gJ3FAKjr;xvxsOVLQWqh;z5rdAD1Z9rH;DWMK6mvF9LH;VHtSG6l59rb",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "Combined Oral contraceptive Pills",
	  "ID": "Combined Oral contraceptive Pills",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;m1U1MJZoK9Q.QvctQfKAQn3;hH9gmEmEhH4.i9dqmLZr7fd;vBtxrMus3Qf",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "Progestin only pills",
	  "ID": "Progestin only pills",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;uiU7PDbqn74.QvctQfKAQn3;dl4JcBnxu0X.i9dqmLZr7fd;H7CkBPdObiC",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "Emergency Contraceptive pills",
	  "ID": "Emergency Contraceptive pills",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;nGR47qCgOfQ.QvctQfKAQn3;qaBPR9wbWku.i9dqmLZr7fd;KWavo9MWGBT",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "Cycle Beads",
	  "ID": "Cycle Beads",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;CxoGtEwF44m.QvctQfKAQn3;bGGT0F7iRxt.i9dqmLZr7fd;E5ehG5Qmk5Y",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "Injectables",
	  "ID": "Injectables",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;CH3syaQ3wJ3.QvctQfKAQn3;J6qnTev1LXw.i9dqmLZr7fd;xvxsOVLQWqh",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "IUCDs",
	  "ID": "IUCDs",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;ri9reJBhA2Y.QvctQfKAQn3;tfPZ6sGgh4q.i9dqmLZr7fd;HP1u3rO8rM7",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "Implants (1-Rod)",
	  "ID": "Implants (1-Rod)",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;QZpWVTFZEE7.QvctQfKAQn3;XgJfT71Unkn.i9dqmLZr7fd;ZbLcoTanQnP",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "Implants (2-Rod)",
	  "ID": "Implants (2-Rod)",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;WLS1R40DxXt.QvctQfKAQn3;MsS41X1GEFr.i9dqmLZr7fd;Zz6gJ3FAKjr",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "Female Condoms",
	  "ID": "Female Condoms",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;RXJmB0afFhv.QvctQfKAQn3;AR7RhdC90IV.i9dqmLZr7fd;z5rdAD1Z9rH",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "Male Condoms",
	  "ID": "Male Condoms",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;YSjqRqkkQdi.QvctQfKAQn3;AVDzuypqGt9.i9dqmLZr7fd;DWMK6mvF9LH",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "Others",
	  "ID": "Others",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;FyLIhJocwlR.QvctQfKAQn3;QKvDccYJ18W.i9dqmLZr7fd;VHtSG6l59rb",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Stock status",
	  "Level": "County",
	  "Name": "All commodities",
	  "ID": "county__all_commodities",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:m1U1MJZoK9Q.QvctQfKAQn3;uiU7PDbqn74.QvctQfKAQn3;nGR47qCgOfQ.QvctQfKAQn3;CxoGtEwF44m.QvctQfKAQn3;CH3syaQ3wJ3.QvctQfKAQn3;ri9reJBhA2Y.QvctQfKAQn3;QZpWVTFZEE7.QvctQfKAQn3;WLS1R40DxXt.QvctQfKAQn3;RXJmB0afFhv.QvctQfKAQn3;YSjqRqkkQdi.QvctQfKAQn3;FyLIhJocwlR.QvctQfKAQn3;hH9gmEmEhH4.i9dqmLZr7fd;dl4JcBnxu0X.i9dqmLZr7fd;qaBPR9wbWku.i9dqmLZr7fd;bGGT0F7iRxt.i9dqmLZr7fd;J6qnTev1LXw.i9dqmLZr7fd;tfPZ6sGgh4q.i9dqmLZr7fd;XgJfT71Unkn.i9dqmLZr7fd;MsS41X1GEFr.i9dqmLZr7fd;AR7RhdC90IV.i9dqmLZr7fd;AVDzuypqGt9.i9dqmLZr7fd;QKvDccYJ18W.i9dqmLZr7fd;vBtxrMus3Qf;H7CkBPdObiC;KWavo9MWGBT;E5ehG5Qmk5Y;xvxsOVLQWqh;HP1u3rO8rM7;ZbLcoTanQnP;Zz6gJ3FAKjr;z5rdAD1Z9rH;DWMK6mvF9LH;VHtSG6l59rb",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "hfVjCurKxh2",
	  "Default Level": 1,
	  "Notes": ""
	},
	{
	  "Page": "",
	  "Level": "",
	  "Name": "",
	  "ID": "",
	  "URLs": "",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Reporting Rate",
	  "Level": "County",
	  "Name": "Reporting Rate Trend",
	  "ID": "county__reporting_rate_trend",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE",
	  "Default Period": "LAST_12_MONTHS",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Reporting Rate",
	  "Level": "County",
	  "Name": "Reporting Rate Trend(on time)",
	  "ID": "county__on-time_reporting_rate_trend",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE_ON_TIME",
	  "Default Period": "LAST_12_MONTHS",
	  "Default Org Unit": "hfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Reporting Rate",
	  "Level": "County",
	  "Name": "Reporting Rate Trend (latest subcounty)",
	  "ID": "county__latest_reporting_rate_subcounty",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=pe:LAST_MONTH&dimension=dx:g3RQRuh8ikd.REPORTING_RATE&dimension=ou:LEVEL-3;HMNARUV2CW4",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "hfVjCurKxh3",
	  "Default Level": 3,
	  "Notes": ""
	},
	{
	  "Page": "Reporting Rate",
	  "Level": "County",
	  "Name": "Facility Reporting Rate",
	  "ID": "county__facility_reporting_rate",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.ACTUAL_REPORTS;g3RQRuh8ikd.EXPECTED_REPORTS",
	  "Default Period": "LAST_6_MONTHS",
	  "Default Org Unit": "vvOK1BxTbet",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Reporting Rate",
	  "Level": "County",
	  "Name": "Subcounty Reporting Rate",
	  "ID": "county__subcounty_reporting_rate",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.ACTUAL_REPORTS;g3RQRuh8ikd.EXPECTED_REPORTS",
	  "Default Period": "LAST_6_MONTHS",
	  "Default Org Unit": "vvOK1BxTbet",
	  "Default Level": 4,
	  "Notes": ""
	},
	{
	  "Page": "Data Quality",
	  "Level": "County",
	  "Name": "Concordance",
	  "ID": "county__dq_concordance",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:AVDzuypqGt9.Cs84jrj1YFp;AVDzuypqGt9.i9dqmLZr7fd",
	  "Default Period": "201911;201912",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Data Quality",
	  "Level": "County",
	  "Name": "Consistency",
	  "ID": "county__dq_consistency",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:AVDzuypqGt9.Cs84jrj1YFp;AVDzuypqGt9.VW51Ep3auXR;AVDzuypqGt9.JQ7EF0X1LIJ;AVDzuypqGt9.to0Pssxkq4S;AVDzuypqGt9.AO6xfSyHuHU;AVDzuypqGt9.i9dqmLZr7fd",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Supply Chain Performance",
	  "Level": "County",
	  "Name": "Indicator Summary",
	  "ID": "county__indicator_summary",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:g3RQRuh8ikd.REPORTING_RATE;g3RQRuh8ikd.REPORTING_RATE_ON_TIME;zLR3PBVPgN5;bJILAolJsSJ;jtGNoWcdNcx;p2aNqT2HVyr",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Supply Chain Performance",
	  "Level": "County",
	  "Name": "Indicator Trends",
	  "ID": "county__indicator_trends",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:HfGVoCZAwtd",
	  "Default Period": "LAST_6_MONTHS",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "",
	  "Level": "",
	  "Name": "",
	  "ID": "",
	  "URLs": "",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Accountability",
	  "Level": "County",
	  "Name": "Accountability",
	  "ID": "county__accountability",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:BnGDrFwyQp9.HWtHCLAwprR;c0MB4RmVjxk.HWtHCLAwprR;qnZmg5tNSMy.HWtHCLAwprR;gVp1KSFI69G.HWtHCLAwprR;iOARK31NdLp.HWtHCLAwprR;imheYfA1Kiw.HWtHCLAwprR;cPlWFYbBacW.HWtHCLAwprR;BnGDrFwyQp9.CckV73xy6HB;gVp1KSFI69G.CckV73xy6HB;qnZmg5tNSMy.CckV73xy6HB;c0MB4RmVjxk.CckV73xy6HB;iOARK31NdLp.CckV73xy6HB;imheYfA1Kiw.CckV73xy6HB;cPlWFYbBacW.CckV73xy6HB;BnGDrFwyQp9.yuvCdaFqdCW;c0MB4RmVjxk.yuvCdaFqdCW;qnZmg5tNSMy.yuvCdaFqdCW;gVp1KSFI69G.yuvCdaFqdCW;iOARK31NdLp.yuvCdaFqdCW;imheYfA1Kiw.yuvCdaFqdCW;cPlWFYbBacW.yuvCdaFqdCW;BnGDrFwyQp9.w77uMi1KzOH;c0MB4RmVjxk.w77uMi1KzOH;qnZmg5tNSMy.w77uMi1KzOH;gVp1KSFI69G.w77uMi1KzOH;iOARK31NdLp.w77uMi1KzOH;imheYfA1Kiw.w77uMi1KzOH;cPlWFYbBacW.w77uMi1KzOH;BnGDrFwyQp9.unVIt2C0cdW;c0MB4RmVjxk.unVIt2C0cdW;qnZmg5tNSMy.unVIt2C0cdW;gVp1KSFI69G.unVIt2C0cdW;iOARK31NdLp.unVIt2C0cdW;imheYfA1Kiw.unVIt2C0cdW;cPlWFYbBacW.unVIt2C0cdW;BnGDrFwyQp9.rPAsF4cpNxm;c0MB4RmVjxk.rPAsF4cpNxm;qnZmg5tNSMy.rPAsF4cpNxm;gVp1KSFI69G.rPAsF4cpNxm;iOARK31NdLp.rPAsF4cpNxm;imheYfA1Kiw.rPAsF4cpNxm;cPlWFYbBacW.rPAsF4cpNxm&displayProperty=NAME&outputIdScheme=UID&data",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 1,
	  "Notes": ""
	},
	{
	  "Page": "Issues vs Receipts",
	  "Level": "County",
	  "Name": "Issues vs Receipts",
	  "ID": "county__issues_vs_receipts",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:jfUzb86mBSP.DTnItSklSr8;HwvUHnslwbh.DTnItSklSr8;OLYLVMDHEj8.DTnItSklSr8;UJeKVZzAnfS.DTnItSklSr8;naztfZrbMtd.DTnItSklSr8;EtG9ozt2joA.DTnItSklSr8;Umi8ZsiqBHw.DTnItSklSr8;BnGDrFwyQp9.yuvCdaFqdCW;c0MB4RmVjxk.yuvCdaFqdCW;qnZmg5tNSMy.yuvCdaFqdCW;gVp1KSFI69G.yuvCdaFqdCW;iOARK31NdLp.yuvCdaFqdCW;imheYfA1Kiw.yuvCdaFqdCW;eFqDcjgvt39.EJ8nUfcupBq&data",
	  "Default Period": "201912;202001",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 1,
	  "Notes": ""
	},
	{
	  "Page": "Health Facility Followup",
	  "Level": "County",
	  "Name": "Understocked Facilities",
	  "ID": "county__understocked_facilities",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:SSARcWY2Ge1;iOARK31NdLp.rPAsF4cpNxm;naztfZrbMtd.miM6uIJ2cWx",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "Health Facility Followup",
	  "Level": "County",
	  "Name": "Overstocked Facilities",
	  "ID": "county__overstocked_facilities",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:SSARcWY2Ge1;iOARK31NdLp.rPAsF4cpNxm;naztfZrbMtd.miM6uIJ2cWx",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": 5,
	  "Notes": ""
	},
	{
	  "Page": "",
	  "Level": "",
	  "Name": "",
	  "ID": "",
	  "URLs": "",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "National Summary",
	  "Level": "National",
	  "Name": "National Summary",
	  "ID": "national__summary",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:HfGVoCZAwtd;nK8sqMAeQHY;ZcngDQJKiEg;wOKbEd8Dbi3;SSARcWY2Ge1;AX1co0SXobM;UUNwkYQhYgX&dimension=ou:HfVjCurKxh2",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "All Malaria Commodities",
	  "Level": "National",
	  "Name": "SOH Comparison",
	  "ID": "national__soh_comparison",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:jfUzb86mBSP.miM6uIJ2cWx;HwvUHnslwbh.miM6uIJ2cWx;OLYLVMDHEj8.miM6uIJ2cWx;UJeKVZzAnfS.miM6uIJ2cWx;naztfZrbMtd.miM6uIJ2cWx;EtG9ozt2joA.miM6uIJ2cWx;Umi8ZsiqBHw.miM6uIJ2cWx;Aui7lNDOsSF.HMTuusGLTUj;iZe9QHpC31Y.HMTuusGLTUj;Kkh8ZtRWFmX.HMTuusGLTUj;E7M967QxxFc.HMTuusGLTUj;Wupc6TOJhcK.HMTuusGLTUj;lZCba7Ijb7x.HMTuusGLTUj;ALnonKSyDct.HMTuusGLTUj;BnGDrFwyQp9.rPAsF4cpNxm;c0MB4RmVjxk.rPAsF4cpNxm;qnZmg5tNSMy.rPAsF4cpNxm;gVp1KSFI69G.rPAsF4cpNxm;iOARK31NdLp.rPAsF4cpNxm;imheYfA1Kiw.rPAsF4cpNxm;cPlWFYbBacW.rPAsF4cpNxm",
	  "Default Period": "LAST_MONTH",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Pending Shipments",
	  "Level": "National",
	  "Name": "Pending Shipments",
	  "ID": "national__pending_shipments",
	  "URLs": "https://hiskenya.org/api/26/dataStore/pending/stocks",
	  "Default Period": "",
	  "Default Org Unit": "",
	  "Default Level": "",
	  "Notes": ""
	},
	{
	  "Page": "Issues vs Receipts",
	  "Level": "National",
	  "Name": "Issues vs Receipts",
	  "ID": "national__issues_vs_receipts",
	  "URLs": "https://hiskenya.org/api/26/analytics.json?dimension=dx:jfUzb86mBSP.DTnItSklSr8;HwvUHnslwbh.DTnItSklSr8;OLYLVMDHEj8.DTnItSklSr8;UJeKVZzAnfS.DTnItSklSr8;naztfZrbMtd.DTnItSklSr8;EtG9ozt2joA.DTnItSklSr8;Umi8ZsiqBHw.DTnItSklSr8;BnGDrFwyQp9.yuvCdaFqdCW;c0MB4RmVjxk.yuvCdaFqdCW;qnZmg5tNSMy.yuvCdaFqdCW;gVp1KSFI69G.yuvCdaFqdCW;iOARK31NdLp.yuvCdaFqdCW;imheYfA1Kiw.yuvCdaFqdCW;eFqDcjgvt39.EJ8nUfcupBq&data",
	  "Default Period": "201912;202001",
	  "Default Org Unit": "HfVjCurKxh2",
	  "Default Level": "",
	  "Notes": ""
	}
  ]

  module.exports = fp
